// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHf4iL2K1LKD2W6UwB1Hb1YYGktq9ytDY',
    appId: '1:439419975672:web:26a4829bbb4ff68c81880d',
    messagingSenderId: '439419975672',
    projectId: 'fasum-d2cbc',
    authDomain: 'fasum-d2cbc.firebaseapp.com',
    databaseURL: 'https://fasum-d2cbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-d2cbc.firebasestorage.app',
    measurementId: 'G-5LPQ9J8SVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9A9IVlu5RmbX_SwaSgMnmRnMq3jYeqT0',
    appId: '1:439419975672:android:afacd13ddab62d3381880d',
    messagingSenderId: '439419975672',
    projectId: 'fasum-d2cbc',
    databaseURL: 'https://fasum-d2cbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-d2cbc.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALNlVfriOdX8Yn5rvHSfOHlKneVRW5f6M',
    appId: '1:439419975672:ios:39a272ce2b0cced081880d',
    messagingSenderId: '439419975672',
    projectId: 'fasum-d2cbc',
    databaseURL: 'https://fasum-d2cbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-d2cbc.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALNlVfriOdX8Yn5rvHSfOHlKneVRW5f6M',
    appId: '1:439419975672:ios:39a272ce2b0cced081880d',
    messagingSenderId: '439419975672',
    projectId: 'fasum-d2cbc',
    databaseURL: 'https://fasum-d2cbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-d2cbc.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHf4iL2K1LKD2W6UwB1Hb1YYGktq9ytDY',
    appId: '1:439419975672:web:dd1235b28c8fd96a81880d',
    messagingSenderId: '439419975672',
    projectId: 'fasum-d2cbc',
    authDomain: 'fasum-d2cbc.firebaseapp.com',
    databaseURL: 'https://fasum-d2cbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-d2cbc.firebasestorage.app',
    measurementId: 'G-3B71WSJ1RL',
  );

}