// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtVFbR1A4IYkL7SMfDmpuxH2K-AB0NdZk',
    appId: '1:784936064919:web:b9d3b3fe27ef25ed9896d2',
    messagingSenderId: '784936064919',
    projectId: 'firstapp-83404',
    authDomain: 'firstapp-83404.firebaseapp.com',
    storageBucket: 'firstapp-83404.firebasestorage.app',
    measurementId: 'G-RN1DSM71LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEY7sNDVaYvlMHFAC7or-UOweGjv6D3c',
    appId: '1:784936064919:android:646ce8fa298c8b399896d2',
    messagingSenderId: '784936064919',
    projectId: 'firstapp-83404',
    storageBucket: 'firstapp-83404.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtVFbR1A4IYkL7SMfDmpuxH2K-AB0NdZk',
    appId: '1:784936064919:web:b3071cca7e50ecc49896d2',
    messagingSenderId: '784936064919',
    projectId: 'firstapp-83404',
    authDomain: 'firstapp-83404.firebaseapp.com',
    storageBucket: 'firstapp-83404.firebasestorage.app',
    measurementId: 'G-RR8JTWEWK5',
  );
}
